/* ===================================================================
   Apple Price Map — app.js
   Loads data.json (generated by apple_price_data.py), draws a USA
   choropleth (D3 + topojson, Albers USA projection) coloured by total
   price (list price + state sales tax), and keeps a sidebar + an
   always-available data table in sync with the same filters.
   =================================================================== */

const TOPOJSON_URL = 'https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json';

// US Census FIPS state code -> USPS postal code (topojson feature ids are FIPS codes)
const FIPS_TO_STATE = {
  1:'AL', 2:'AK', 4:'AZ', 5:'AR', 6:'CA', 8:'CO', 9:'CT', 10:'DE', 11:'DC', 12:'FL',
  13:'GA', 15:'HI', 16:'ID', 17:'IL', 18:'IN', 19:'IA', 20:'KS', 21:'KY', 22:'LA', 23:'ME',
  24:'MD', 25:'MA', 26:'MI', 27:'MN', 28:'MS', 29:'MO', 30:'MT', 31:'NE', 32:'NV', 33:'NH',
  34:'NJ', 35:'NM', 36:'NY', 37:'NC', 38:'ND', 39:'OH', 40:'OK', 41:'OR', 42:'PA', 44:'RI',
  45:'SC', 46:'SD', 47:'TN', 48:'TX', 49:'UT', 50:'VT', 51:'VA', 53:'WA', 54:'WV', 55:'WI',
  56:'WY', 72:'PR',
};

// Sequential blue ramp (validated palette, step 100 -> 700; lightest = cheapest)
const SEQ_RAMP = ['#cde2fb','#9ec5f4','#6da7ec','#3987e5','#256abf','#184f95','#0d366b'];

// Compact ZIP3 -> state ranges, mirrors apple_price_data.py's ZIP_STATE_RANGES
const ZIP_STATE_RANGES = [
  [0,9,'PR'],[10,27,'MA'],[28,29,'RI'],[30,38,'NH'],[39,49,'ME'],[50,59,'VT'],[60,69,'CT'],
  [70,89,'NJ'],[100,149,'NY'],[150,196,'PA'],[197,199,'DE'],[200,205,'DC'],[206,219,'MD'],
  [220,246,'VA'],[247,268,'WV'],[270,289,'NC'],[290,299,'SC'],[300,319,'GA'],[398,399,'GA'],
  [320,349,'FL'],[350,369,'AL'],[370,385,'TN'],[386,397,'MS'],[400,427,'KY'],[430,459,'OH'],
  [460,479,'IN'],[480,499,'MI'],[500,528,'IA'],[530,549,'WI'],[550,567,'MN'],[570,577,'SD'],
  [580,588,'ND'],[590,599,'MT'],[600,629,'IL'],[630,658,'MO'],[660,679,'KS'],[680,693,'NE'],
  [700,714,'LA'],[716,729,'AR'],[730,749,'OK'],[750,799,'TX'],[885,885,'TX'],[800,816,'CO'],
  [820,831,'WY'],[832,838,'ID'],[840,847,'UT'],[850,865,'AZ'],[870,884,'NM'],[889,898,'NV'],
  [900,961,'CA'],[967,968,'HI'],[970,979,'OR'],[980,994,'WA'],[995,999,'AK'],
];

// ------------------------------------------------------------------
// State
// ------------------------------------------------------------------
let DATA = null;               // parsed data.json
let currentProductId = null;
let selectedVariant = {};
let employeeOn = false;
let employeePct = 15;
let pinnedState = null;
let sortKey = 'total_price';
let sortDir = 'asc';
let usStatesGeo = null;        // topojson -> geojson features, cached after first load
let isLight = false;

// ------------------------------------------------------------------
// Helpers
// ------------------------------------------------------------------
const $ = (id) => document.getElementById(id);
const fmtUsd = (v) => new Intl.NumberFormat('en-US', { style:'currency', currency:'USD', maximumFractionDigits:0 }).format(v);
const fmtUsd2 = (v) => new Intl.NumberFormat('en-US', { style:'currency', currency:'USD', maximumFractionDigits:2 }).format(v);

function getProduct(id){ return DATA.products.find(p => p.id === id); }

function defaultVariantSelection(product){
  const sel = {};
  Object.keys(product.variants || {}).forEach(dim => { sel[dim] = product.variants[dim][0].id; });
  return sel;
}
function variantDelta(product){
  let total = 0;
  Object.keys(product.variants || {}).forEach(dim => {
    const opt = product.variants[dim].find(o => o.id === selectedVariant[dim]);
    if (opt) total += opt.delta;
  });
  return total;
}
function effectiveUsd(product){ return product.usd + variantDelta(product); }

function computeStateRow(state, baseUsd){
  const taxRate = state.tax_rate_pct / 100;
  const discounted = baseUsd * (1 - (employeeOn ? employeePct/100 : 0));
  const taxAmount = discounted * taxRate;
  const total = discounted + taxAmount;
  return { code: state.code, name: state.name, tax_rate_pct: state.tax_rate_pct,
           base_price: discounted, tax_amount: taxAmount, total_price: total };
}

function allStateRows(){
  const product = getProduct(currentProductId);
  const base = effectiveUsd(product);
  return DATA.us_states.map(s => computeStateRow(s, base));
}

function zip3ToState(zip3){
  for (const [lo, hi, state] of ZIP_STATE_RANGES){ if (zip3 >= lo && zip3 <= hi) return state; }
  return null;
}

// ------------------------------------------------------------------
// Color scale — sequential, single hue, light (cheap) -> dark (pricey)
// ------------------------------------------------------------------
function makeColorScale(rows){
  const values = rows.map(r => r.total_price);
  const min = Math.min(...values), max = Math.max(...values);
  const domain = SEQ_RAMP.map((_, i) => min + (max - min) * (i / (SEQ_RAMP.length - 1)));
  const scale = d3.scaleLinear().domain(domain).range(SEQ_RAMP).clamp(true);
  return { scale, min, max };
}

// ------------------------------------------------------------------
// Filter controls
// ------------------------------------------------------------------
function populateProductSelect(){
  const sel = $('productSelect');
  const cats = [...new Set(DATA.products.map(p => p.cat))];
  sel.innerHTML = cats.map(cat => `
    <optgroup label="${cat}">
      ${DATA.products.filter(p => p.cat === cat).map(p => `<option value="${p.id}">${p.name} — $${p.usd}</option>`).join('')}
    </optgroup>
  `).join('');
  sel.value = currentProductId;
}

function renderVariantFields(){
  const product = getProduct(currentProductId);
  const wrap = $('variantFields');
  const dims = Object.keys(product.variants || {});
  if (dims.length === 0){ wrap.innerHTML = ''; return; }
  wrap.innerHTML = dims.map(dim => {
    const opts = product.variants[dim];
    const label = dim.charAt(0).toUpperCase() + dim.slice(1);
    return `
      <div class="f-field">
        <label class="f-label" for="v-${dim}">${label}</label>
        <select id="v-${dim}" data-dim="${dim}" class="variant-select">
          ${opts.map(o => `<option value="${o.id}" ${selectedVariant[dim]===o.id?'selected':''}>${o.label}${o.delta?' (+$'+o.delta+')':''}</option>`).join('')}
        </select>
      </div>`;
  }).join('');
  wrap.querySelectorAll('.variant-select').forEach(s => {
    s.addEventListener('change', e => { selectedVariant[e.target.dataset.dim] = e.target.value; renderAll(); });
  });
}

// ------------------------------------------------------------------
// Map drawing
// ------------------------------------------------------------------
let svgSel = null, pathGen = null, projection = null;

async function loadTopology(){
  if (usStatesGeo) return usStatesGeo;
  const topo = await d3.json(TOPOJSON_URL);
  const featureCollection = topojson.feature(topo, topo.objects.states);
  usStatesGeo = featureCollection.features;
  return usStatesGeo;
}

async function initMap(){
  const svg = d3.select('#usMap');
  svgSel = svg;
  projection = d3.geoAlbersUsa().translate([487.5, 305]).scale(1200);
  pathGen = d3.geoPath().projection(projection);

  try{
    const features = await loadTopology();
    $('mapLoading').hidden = true;
    svg.selectAll('path.state')
      .data(features, d => d.id)
      .join('path')
      .attr('class', 'state')
      .attr('d', pathGen)
      .attr('tabindex', 0)
      .attr('data-fips', d => d.id)
      .on('pointermove', onStateHover)
      .on('pointerleave', onStateLeave)
      .on('focus', onStateHover)
      .on('blur', onStateLeave)
      .on('click', onStateClick)
      .on('keydown', e => { if (e.key === 'Enter' || e.key === ' '){ e.preventDefault(); onStateClick(e); } });
    updateMapColors();
  }catch(err){
    $('mapLoading').textContent = 'Could not load the US map outline (network blocked?). The table view below still has every number.';
  }
}

// Topology feature ids are zero-padded FIPS strings (e.g. "06" for California) —
// normalize with parseInt before looking them up.
function fipsToState(id){ return FIPS_TO_STATE[parseInt(id, 10)] || null; }

function stateCodeFromEvent(e){
  return fipsToState(e.target.getAttribute('data-fips'));
}

function updateMapColors(){
  if (!svgSel) return;
  const rows = allStateRows();
  const byCode = Object.fromEntries(rows.map(r => [r.code, r]));
  const { scale, min, max } = makeColorScale(rows);
  window.__currentRows = rows;
  window.__currentByCode = byCode;
  window.__currentScale = scale;

  svgSel.selectAll('path.state')
    .classed('no-data', d => !byCode[fipsToState(d.id)])
    .classed('pinned', d => pinnedState === fipsToState(d.id))
    .attr('fill', d => {
      const row = byCode[fipsToState(d.id)];
      return row ? scale(row.total_price) : '#555';
    })
    .attr('aria-label', d => {
      const row = byCode[fipsToState(d.id)];
      return row ? `${row.name}: ${fmtUsd(row.total_price)} total` : '';
    });

  $('legendMin').textContent = fmtUsd(min);
  $('legendMax').textContent = fmtUsd(max);
}

function onStateHover(e){
  const code = stateCodeFromEvent(e);
  const row = window.__currentByCode && window.__currentByCode[code];
  if (!row) return;
  e.target.classList.add('hovered');
  const tt = $('tooltip');
  tt.hidden = false;
  tt.innerHTML = `
    <div class="tt-state">${row.name}</div>
    <div class="tt-row"><span>Price before tax</span><span class="v">${fmtUsd2(row.base_price)}</span></div>
    <div class="tt-row"><span>Tax (${row.tax_rate_pct.toFixed(2)}%)</span><span class="v">${fmtUsd2(row.tax_amount)}</span></div>
    <div class="tt-row total"><span>Total price</span><span class="v">${fmtUsd2(row.total_price)}</span></div>
  `;
  const stage = $('mapStage');
  const stageBox = stage.getBoundingClientRect();
  let x, y;
  if (e.clientX !== undefined && e.type === 'pointermove'){
    x = e.clientX - stageBox.left;
    y = e.clientY - stageBox.top;
  } else {
    const box = e.target.getBoundingClientRect();
    x = box.left + box.width/2 - stageBox.left;
    y = box.top - stageBox.top;
  }
  tt.style.left = x + 'px';
  tt.style.top = y + 'px';
}
function onStateLeave(e){
  e.target.classList.remove('hovered');
  $('tooltip').hidden = true;
}
function onStateClick(e){
  const code = stateCodeFromEvent(e);
  if (!code) return;
  pinnedState = pinnedState === code ? null : code;
  updateMapColors();
}

// ------------------------------------------------------------------
// Sidebar stats + rank lists
// ------------------------------------------------------------------
function renderStats(rows){
  const sorted = rows.slice().sort((a,b) => a.total_price - b.total_price);
  const cheapest = sorted[0], priciest = sorted[sorted.length - 1];
  const spread = priciest.total_price - cheapest.total_price;

  $('statRow').innerHTML = `
    <div class="stat"><div class="k">Cheapest</div>
      <div class="v good">${cheapest.name}</div>
      <div class="d">${fmtUsd2(cheapest.total_price)}</div></div>
    <div class="stat"><div class="k">Most expensive</div>
      <div class="v bad">${priciest.name}</div>
      <div class="d">${fmtUsd2(priciest.total_price)}</div></div>
    <div class="stat"><div class="k">Spread</div>
      <div class="v">${fmtUsd2(spread)}</div>
      <div class="d">${((spread/cheapest.total_price)*100).toFixed(1)}% more at the priciest state</div></div>
  `;

  $('cheapList').innerHTML = sorted.slice(0,5).map(r => `<li><span class="name">${r.name}</span><span class="price num">${fmtUsd2(r.total_price)}</span></li>`).join('');
  $('cheapList').className = 'rank-list cheap';
  $('pricyList').innerHTML = sorted.slice(-5).reverse().map(r => `<li><span class="name">${r.name}</span><span class="price num">${fmtUsd2(r.total_price)}</span></li>`).join('');
  $('pricyList').className = 'rank-list pricy';
}

// ------------------------------------------------------------------
// Table view (accessible, always-available alternative to the map)
// ------------------------------------------------------------------
function renderTable(rows){
  const cheapest = Math.min(...rows.map(r => r.total_price));
  const sorted = rows.slice().sort((a,b) => {
    const dir = sortDir === 'asc' ? 1 : -1;
    if (typeof a[sortKey] === 'string') return a[sortKey].localeCompare(b[sortKey]) * dir;
    return (a[sortKey] - b[sortKey]) * dir;
  });
  $('stateTableBody').innerHTML = sorted.map(r => {
    const isBest = r.total_price === cheapest;
    const diff = r.total_price - cheapest;
    return `
      <tr class="${isBest ? 'best' : ''}">
        <td>${r.name}</td>
        <td class="num-col">${r.tax_rate_pct.toFixed(2)}%</td>
        <td class="num-col">${fmtUsd2(r.base_price)}</td>
        <td class="num-col">${fmtUsd2(r.tax_amount)}</td>
        <td class="num-col">${fmtUsd2(r.total_price)}</td>
        <td class="num-col">${isBest ? '—' : '+' + fmtUsd2(diff)}</td>
      </tr>`;
  }).join('');
}

// ------------------------------------------------------------------
// Main render
// ------------------------------------------------------------------
function renderAll(){
  const product = getProduct(currentProductId);
  const base = effectiveUsd(product);
  $('mapTitle').textContent = `Price by state — ${product.name}`;
  $('mapSub').textContent = `Base list price ${fmtUsd(base)}${employeeOn ? ` · ${employeePct}% employee discount applied` : ''} · then each state's sales tax`;

  const rows = allStateRows();
  updateMapColors();
  renderStats(rows);
  renderTable(rows);
  // A filter change invalidates whatever a lingering tooltip is showing —
  // hide it rather than let it display stale numbers until the next hover.
  $('tooltip').hidden = true;
}

// ------------------------------------------------------------------
// Wiring
// ------------------------------------------------------------------
function wireEvents(){
  $('productSelect').addEventListener('change', e => {
    currentProductId = e.target.value;
    selectedVariant = defaultVariantSelection(getProduct(currentProductId));
    renderVariantFields();
    renderAll();
  });

  $('employeeToggle').addEventListener('change', e => {
    employeeOn = e.target.checked;
    $('employeeToggleWrap').classList.toggle('on', employeeOn);
    renderAll();
  });
  $('employeePct').addEventListener('change', e => { employeePct = parseFloat(e.target.value) || 0; renderAll(); });

  $('zipBtn').addEventListener('click', () => {
    const zip = $('zipInput').value.trim();
    const statusEl = $('zipStatus');
    if (!/^\d{5}$/.test(zip)){
      statusEl.hidden = false; statusEl.className = 'status-msg err';
      statusEl.textContent = 'Enter a 5-digit US ZIP code.';
      return;
    }
    const state = zip3ToState(parseInt(zip.slice(0,3), 10));
    if (!state || !window.__currentByCode[state]){
      statusEl.hidden = false; statusEl.className = 'status-msg err';
      statusEl.textContent = "Couldn't match that ZIP to a state in the data.";
      return;
    }
    pinnedState = state;
    updateMapColors();
    const row = window.__currentByCode[state];
    statusEl.hidden = false; statusEl.className = 'status-msg ok';
    statusEl.textContent = `${row.name}: ${fmtUsd2(row.total_price)} total (${row.tax_rate_pct.toFixed(2)}% tax). Highlighted on the map.`;
  });
  $('zipInput').addEventListener('keydown', e => { if (e.key === 'Enter') $('zipBtn').click(); });

  $('viewMapBtn').addEventListener('click', () => {
    $('viewMapBtn').classList.add('on'); $('viewTableBtn').classList.remove('on');
    $('mapStage').hidden = false; $('legend').hidden = false; document.querySelector('.legend-caption').hidden = false;
    $('tableWrap').hidden = true;
  });
  $('viewTableBtn').addEventListener('click', () => {
    $('viewTableBtn').classList.add('on'); $('viewMapBtn').classList.remove('on');
    $('mapStage').hidden = true; $('legend').hidden = true; document.querySelector('.legend-caption').hidden = true;
    $('tableWrap').hidden = false;
  });

  document.querySelectorAll('#stateTable thead th[data-sort]').forEach(th => {
    th.addEventListener('click', () => {
      const key = th.dataset.sort;
      if (sortKey === key) sortDir = sortDir === 'asc' ? 'desc' : 'asc';
      else { sortKey = key; sortDir = 'asc'; }
      renderTable(allStateRows());
    });
  });

  $('themeBtn').addEventListener('click', () => {
    isLight = !isLight;
    document.documentElement.setAttribute('data-theme', isLight ? 'light' : 'dark');
    $('themeBtn').textContent = isLight ? '☀️ Light' : '🌙 Dark';
  });
}

// ------------------------------------------------------------------
// Init
// ------------------------------------------------------------------
async function init(){
  // Sync the toggle's label to whatever theme the browser is actually
  // rendering (system preference) before the user has clicked it at all.
  isLight = !!(window.matchMedia && window.matchMedia('(prefers-color-scheme: light)').matches);
  $('themeBtn').textContent = isLight ? '☀️ Light' : '🌙 Dark';

  const res = await fetch('data.json');
  DATA = await res.json();
  currentProductId = DATA.products.find(p => p.id === 'ip17pro') ? 'ip17pro' : DATA.products[0].id;
  selectedVariant = defaultVariantSelection(getProduct(currentProductId));

  populateProductSelect();
  renderVariantFields();
  wireEvents();
  await initMap();
  renderAll();
}
init();
